build_environment: ubuntu1304
language: java
jdk: oraclejdk7

before_install:
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
  - unzip gradle-1.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.6
  - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle assemble
notifications:
  email: false
  campfire:
    rooms:
      - shippable:1796c91e312c6383e6e2a348849881da56bcde00@575797
    template:
      - "%{repository} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
